export enum Event {
  onPagination,
  onOrder,
  onGlobalSearch,
  onSearch,
  onClick,
  onDoubleClick,
  onCheckboxSelect,
  onSelectAll,
  onColumnResizeMouseDown,
  onColumnResizeMouseMove,
  onColumnResizeMouseUp,
  onRowDrag,
  onRowDrop,
  onRowCollapsedShow,
  onRowCollapsedHide,
  onRowContextMenu,
}
