export const data = [
  {
    phone: '+1 (989) 498-3943',
    age: 26,
    company: 'ZOID',
    name: 'Winters Gill',
    isActive: false,
    company2: 'PROVIDCO',
    company3: 'PLASMOX',
    company4: 'CUJO',
    company5: 'MARTGO',
    company6: 'BARKARAMA',
    company7: 'COLUMELLA',
    company8: 'ZEPITOPE',
    company9: 'MANGLO',
    company10: 'PLUTORQUE',
    company11: 'NIMON',
    company12: 'PYRAMIA',
    company13: 'KENGEN',
    company14: 'NURPLEX',
    company15: 'DOGNOSIS',
    company16: 'VINCH',
    company17: 'PYRAMAX',
    company18: 'ORBOID',
    company19: 'GONKLE',
  },
  {
    phone: '+1 (823) 579-2957',
    age: 29,
    company: 'IPLAX',
    name: 'Arline Juarez',
    isActive: true,
    company2: 'AMTAP',
    company3: 'GENEKOM',
    company4: 'RONBERT',
    company5: 'EZENT',
    company6: 'XEREX',
    company7: 'PATHWAYS',
    company8: 'AVENETRO',
    company9: 'BOSTONIC',
    company10: 'OZEAN',
    company11: 'XOGGLE',
    company12: 'COMCUR',
    company13: 'ENQUILITY',
    company14: 'BIOSPAN',
    company15: 'COMTENT',
    company16: 'BUNGA',
    company17: 'COMBOGEN',
    company18: 'LUNCHPAD',
    company19: 'VETRON',
  },
  {
    phone: '+1 (814) 562-2560',
    age: 22,
    company: 'PROSURE',
    name: 'Middleton Dawson',
    isActive: false,
    company2: 'ZOSIS',
    company3: 'KRAGGLE',
    company4: 'ZILIDIUM',
    company5: 'FLUMBO',
    company6: 'ZILLACTIC',
    company7: 'PHARMEX',
    company8: 'RECOGNIA',
    company9: 'SILODYNE',
    company10: 'ENOMEN',
    company11: 'EMTRAC',
    company12: 'XIIX',
    company13: 'QUARX',
    company14: 'ACCUFARM',
    company15: 'GAPTEC',
    company16: 'PHOLIO',
    company17: 'SNACKTION',
    company18: 'EYERIS',
    company19: 'MULTRON',
  },
  {
    phone: '+1 (852) 562-3375',
    age: 28,
    company: 'DYMI',
    name: 'Joseph Dillard',
    isActive: true,
    company2: 'HOMELUX',
    company3: 'KIGGLE',
    company4: 'ELPRO',
    company5: 'ORBIXTAR',
    company6: 'REMOTION',
    company7: 'DARWINIUM',
    company8: 'CEPRENE',
    company9: 'AQUASSEUR',
    company10: 'FITCORE',
    company11: 'WATERBABY',
    company12: 'BLEEKO',
    company13: 'EXOSWITCH',
    company14: 'HONOTRON',
    company15: 'EQUICOM',
    company16: 'VERAQ',
    company17: 'UBERLUX',
    company18: 'SPRINGBEE',
    company19: 'INSOURCE',
  },
  {
    phone: '+1 (945) 428-3161',
    age: 22,
    company: 'EXTRAWEAR',
    name: 'Kline Clay',
    isActive: false,
    company2: 'LUDAK',
    company3: 'AQUOAVO',
    company4: 'KYAGURU',
    company5: 'FISHLAND',
    company6: 'QNEKT',
    company7: 'SPORTAN',
    company8: 'PARAGONIA',
    company9: 'ISOTRACK',
    company10: 'VIASIA',
    company11: 'MOBILDATA',
    company12: 'FOSSIEL',
    company13: 'NETROPIC',
    company14: 'SEQUITUR',
    company15: 'CENTURIA',
    company16: 'DIGIAL',
    company17: 'VISALIA',
    company18: 'PURIA',
    company19: 'NETUR',
  },
  {
    phone: '+1 (990) 560-3767',
    age: 31,
    company: 'NSPIRE',
    name: 'Osborn Randolph',
    isActive: false,
    company2: 'EXOSIS',
    company3: 'GEEKUS',
    company4: 'SHEPARD',
    company5: 'SYNTAC',
    company6: 'INQUALA',
    company7: 'RUGSTARS',
    company8: 'VALPREAL',
    company9: 'SECURIA',
    company10: 'ZORK',
    company11: 'ZIDOX',
    company12: 'DATAGEN',
    company13: 'OLUCORE',
    company14: 'DOGNOST',
    company15: 'DIGINETIC',
    company16: 'INDEXIA',
    company17: 'ROCKLOGIC',
    company18: 'EYEWAX',
    company19: 'RODEOLOGY',
  },
  {
    phone: '+1 (979) 478-3694',
    age: 26,
    company: 'INTRADISK',
    name: 'Gallagher Logan',
    isActive: false,
    company2: 'QUOTEZART',
    company3: 'COMVENE',
    company4: 'PHUEL',
    company5: 'AQUAMATE',
    company6: 'OMNIGOG',
    company7: 'UNDERTAP',
    company8: 'TELEQUIET',
    company9: 'DIGIRANG',
    company10: 'SQUISH',
    company11: 'ZENTHALL',
    company12: 'KATAKANA',
    company13: 'PLASTO',
    company14: 'COMTEXT',
    company15: 'PLAYCE',
    company16: 'ZYTRAX',
    company17: 'EXOSPEED',
    company18: 'CORIANDER',
    company19: 'GENMEX',
  },
  {
    phone: '+1 (864) 537-2430',
    age: 40,
    company: 'ZAYA',
    name: 'Augusta Cardenas',
    isActive: false,
    company2: 'TECHADE',
    company3: 'NEBULEAN',
    company4: 'IRACK',
    company5: 'APEXTRI',
    company6: 'VIDTO',
    company7: 'MUSANPOLY',
    company8: 'DUOFLEX',
    company9: 'OPTICALL',
    company10: 'INSURITY',
    company11: 'KANGLE',
    company12: 'PLASMOSIS',
    company13: 'LYRICHORD',
    company14: 'NEWCUBE',
    company15: 'STELAECOR',
    company16: 'SYNKGEN',
    company17: 'CAXT',
    company18: 'ZOLAVO',
    company19: 'SPLINX',
  },
  {
    phone: '+1 (920) 467-2733',
    age: 25,
    company: 'QUORDATE',
    name: 'Rivers Fuller',
    isActive: false,
    company2: 'OMATOM',
    company3: 'AQUAFIRE',
    company4: 'PROGENEX',
    company5: 'SUREMAX',
    company6: 'ZOLARITY',
    company7: 'ARTWORLDS',
    company8: 'ILLUMITY',
    company9: 'GEOFORM',
    company10: 'BULLJUICE',
    company11: 'POSHOME',
    company12: 'KAGGLE',
    company13: 'GRUPOLI',
    company14: 'XYLAR',
    company15: 'HELIXO',
    company16: 'EMPIRICA',
    company17: 'KINDALOO',
    company18: 'NEXGENE',
    company19: 'ZAJ',
  },
  {
    phone: '+1 (933) 424-3413',
    age: 22,
    company: 'FURNITECH',
    name: 'Virgie Sloan',
    isActive: false,
    company2: 'EXERTA',
    company3: 'ENDIPIN',
    company4: 'ISBOL',
    company5: 'FUTURIS',
    company6: 'CHILLIUM',
    company7: 'OVERPLEX',
    company8: 'APEX',
    company9: 'HIVEDOM',
    company10: 'STROZEN',
    company11: 'TYPHONICA',
    company12: 'QUILTIGEN',
    company13: 'SOLAREN',
    company14: 'EWAVES',
    company15: 'ENDIPINE',
    company16: 'AUSTECH',
    company17: 'PARLEYNET',
    company18: 'PEARLESEX',
    company19: 'SLOFAST',
  },
  {
    phone: '+1 (966) 590-3885',
    age: 26,
    company: 'SENTIA',
    name: 'Haley Barry',
    isActive: false,
    company2: 'GLUID',
    company3: 'COMVOY',
    company4: 'KNOWLYSIS',
    company5: 'ACRUEX',
    company6: 'FUELWORKS',
    company7: 'GALLAXIA',
    company8: 'SUPPORTAL',
    company9: 'TURNABOUT',
    company10: 'EXTRO',
    company11: 'TRI@TRIBALOG',
    company12: 'SOFTMICRO',
    company13: 'ISOSWITCH',
    company14: 'SPHERIX',
    company15: 'CONJURICA',
    company16: 'QIMONK',
    company17: 'ARCHITAX',
    company18: 'LUMBREX',
    company19: 'BOILCAT',
  },
  {
    phone: '+1 (940) 581-3435',
    age: 37,
    company: 'PARCOE',
    name: 'Marquez Lang',
    isActive: false,
    company2: 'ACCIDENCY',
    company3: 'ZOLAREX',
    company4: 'INSURESYS',
    company5: 'ZOXY',
    company6: 'WAZZU',
    company7: 'ERSUM',
    company8: 'HOTCAKES',
    company9: 'ANARCO',
    company10: 'DATAGENE',
    company11: 'TASMANIA',
    company12: 'GRAINSPOT',
    company13: 'TOURMANIA',
    company14: 'LIMOZEN',
    company15: 'CUBIX',
    company16: 'CIPROMOX',
    company17: 'PLEXIA',
    company18: 'PROTODYNE',
    company19: 'EARWAX',
  },
  {
    phone: '+1 (962) 517-3680',
    age: 25,
    company: 'KLUGGER',
    name: 'Short James',
    isActive: false,
    company2: 'EXTREMO',
    company3: 'KEEG',
    company4: 'NAXDIS',
    company5: 'MAROPTIC',
    company6: 'FUTURIZE',
    company7: 'FURNIGEER',
    company8: 'SATIANCE',
    company9: 'BOINK',
    company10: 'REVERSUS',
    company11: 'SLOGANAUT',
    company12: 'DOGTOWN',
    company13: 'EARTHPURE',
    company14: 'BUZZMAKER',
    company15: 'ZYTREX',
    company16: 'ZILPHUR',
    company17: 'ZENSURE',
    company18: 'ASSISTIA',
    company19: 'CODAX',
  },
  {
    phone: '+1 (907) 466-3011',
    age: 29,
    company: 'DIGIFAD',
    name: 'Susana Humphrey',
    isActive: false,
    company2: 'VENDBLEND',
    company3: 'MICROLUXE',
    company4: 'ORGANICA',
    company5: 'XURBAN',
    company6: 'DREAMIA',
    company7: 'EARTHWAX',
    company8: 'QOT',
    company9: 'TETAK',
    company10: 'VIXO',
    company11: 'SCENTY',
    company12: 'UNI',
    company13: 'UPLINX',
    company14: 'BIOLIVE',
    company15: 'BIZMATIC',
    company16: 'EXPOSA',
    company17: 'QUILK',
    company18: 'BEZAL',
    company19: 'FUTURITY',
  },
  {
    phone: '+1 (966) 576-3230',
    age: 38,
    company: 'ZANYMAX',
    name: 'Gentry Lowe',
    isActive: false,
    company2: 'SULFAX',
    company3: 'EXIAND',
    company4: 'CANDECOR',
    company5: 'ENERFORCE',
    company6: 'INRT',
    company7: 'AFFLUEX',
    company8: 'MEMORA',
    company9: 'CIRCUM',
    company10: 'ECRATIC',
    company11: 'DAYCORE',
    company12: 'IMAGINART',
    company13: 'LIQUIDOC',
    company14: 'COMVERGES',
    company15: 'STEELFAB',
    company16: 'NETPLAX',
    company17: 'WAAB',
    company18: 'PAWNAGRA',
    company19: 'BLANET',
  },
];
